---
title: "1925-1950"
date: 2018-10-14T22:22:57Z
draft: false
---
= 1925 -- 1950

Im Februar 1925 -- einer Zeit der Arbeitslosigkeit und der wirtschaftlichen Not -- fanden sich an die 50 musikbegeisterte Männer aus Leopoldsdorf unter der Leitung des Kapellmeisters Andreas Gebhart zusammen, um ihre Musikbegeisterung in die Tat umzusetzen.
Sie lernten Noten lesen, Harmonielehre, das Spielen der Instrumente und das Marschieren.
Die Musikinstrumente wurden aus eigenen Mitteln -- oft zu zweit -- angeschafft.
Leopold Koller, der Hauptinitiator, setzte sein Haus samt Grundstück als Pfand ein, um die nötigen finanziellen Mittel zum Ankauf weiterer Instrumente bereitstellen zu können.
Nun konnten von Kapellmeister Gottlieb Ostadal auch die erforderlichen Noten angekauft werden.

Der Weg zur Gründung des Leopoldsdorfer Musikvereins war damit geebnet.
Im Jahre 1926 gründete dann eine Gruppe von Männern aus der Arbeiterbewegung den Arbeitermusikverein Leopoldsdorf, dem 40 Musiker angehörten.

Als erster Vorstand wurde gewählt:

Obmann:: Franz Kobliha
Obmann-Stv.:: Leopold Koller
Schriftführer:: Leopold Zoubek
Kassier:: Otto Zoubek
Kapellmeister:: Andreas Gebhart

Am 1. Mai 1926 fand die erste Ausrückung statt, bei der die Bevölkerung von Leopoldsdorf lebhaften Beifall spendete, ein echter Ansporn für die jungen Musiker!
Im Laufe der folgenden Jahre bestritt der Verein Wertungsspiele in Dörfles und Stammersdorf und konnte damit Leopoldsdorf über seine Gemeindegrenzen hinaus musikalisch vertreten.
Seine erste Krise erlebte der Verein im Jahre 1928, als Kapellmeister Andreas Gebhart sein Amt niederlegte.
In dieser schwierigen Situation übernahm der junge Musiker Ferdinand Orth die Agenden des Kapellmeisters und führte den Verein mit nur 16 Musikern weiter.
Einen Aufschwung erlebte die Kapelle 1933, als der aus der Hauptschule Lassee nach Leopoldsdorf versetzte Fachlehrer Armin Gruber als Kapellmeister gewonnen werden konnte.
Gruber war nicht nur Lehrer, Komponist, Chorleiter und Kapellmeister, er war einfach virtuos und ein Meister im Improvisieren.
Unter seiner stets lächelnden Stabführung gab er jedem Lernenden das Gefühl der Sicherheit und der Freude an der Musik.
Er machte allen Mut und spornte sie zu noch größerem Einsatz an.

Dann brachte das politisch verhängnisvolle Jahr 1934 ein Ende des Vereins.
Von der Bezirkshauptmannschaft wurde ein Vereinsverbot erlassen und somit auch der Arbeitermusikverein aufgelöst.
Die Vereinskassa und einige Instrumente wurden beschlagnahmt.
Glücklicherweise konnten jedoch die meisten Instrumente als persönliches Eigentum deklariert und vereinseigene Gegenstände auf dem Dachboden des Rathauses deponiert werden.
Erst nach der Auflösung der Sozialdemokratischen Partei wurde in Leopoldsdorf das öffentliche Musizieren wieder gestattet, allerdings unter der Auflage, dass die Mitglieder des "`Arbeitermusikvereins`" und des "`Männergesangsvereins`" unter dem Namen Musikverein Leopoldsdorf einen neuen Verein gründen und einen neuen Vereinsvorstand wählen sollten.
Dieser neue Musikverein trat das Erbe des Arbeitermusikvereins im Leopoldsdorfer Musikschaffens an.

Der neu gewählte Obmann Johann Artbauer löste die beschlagnahmten Instrumente bei der Bezirkshauptmannschaft aus und unter Kapellmeister Ferdinand Orth ging es wieder aufwärts, so dass der neue Kassier, Josef Zier, bald von voller Kassa berichten konnte.
Willi Vanek (Schriftführer) und Franz Varecha (Kassier- Stellvertreter) unterstützten die Vereinsarbeit.
Jeden Sonntag wurde im Park ein Platzkonzert abgehalten.

Der Großteil der Musiker bildete mit ihren Angehörigen eine dem Verein angeschlossene Theatergruppe, wie dies zu jener Zeit üblich war.
Mit den Erlösen aus den Veranstaltungen konnten Urlaubsfahrten bis nach Salzburg unternommen werden und der seit 1934 als Protektor fungierende Baron von Wiener-Welten in Goldegg besucht werden.
Die Fahrtkosten konnten stets aus der Vereinskasse beglichen werden.

Mit der Machtübernahme der Nationalsozialisten in Österreich im Jahre 1938 wurde der Musikverein abermals reduziert.
Einige Musiker hörten auf zu spielen, andere mussten zum Militär.
Trotzdem wurde so lange gespielt, wie noch Musiker da waren, die vom Krieg verschont geblieben waren.
Nach den überstandenen Leiden und Entbehrungen der Kriegsjahre fanden sich 1945 einige altbewährte Vereinsmitglieder zusammen, um gemeinsam mit jungen Musikern unter der Leitung von Kapellmeister Leopold Varecha die Probenarbeit wieder aufzunehmen.
Mit der 16 Mann starken Kapelle konnte 1946 wieder bei festlichen Anlässen in Kirche und Gemeinde gespielt werden.
Wichtige Verstärkung erhielt der Verein im Jahre 1949, als sich aus wirtschaftlichen Gründen die Jugendkapelle anschloss.

Als erster Obmann nach der Zusammenlegung wurde der heutige Chorleiter Karl Handschuh gewählt.
Doch bereits ein Jahr später legte er sein Amt zurück, und der Musikverein wurde bis zur nächsten Wahl von Karl Ivanics geleitet.
