---
title: "1950-1960"
date: 2018-10-14T22:22:57Z
draft: false
---
= 1950 -- 1960

Am 4. Juni 1950 wurde in Lassee das erste Bezirksmusikfest abgehalten, an dem auch unser Verein teilnahm.
1951 wurde Ferdinand Hehenberger zum Obmann gewählt.
Ihm zur Seite standen Alois Makoschitz als Kapellmeister, Rudolf Neumann als Kassier und Paul Petraschek als Schriftführer.
In dieser Zeit erlebte der Verein einen beachtlichen Aufschwung.
Aber schon bei der nächsten Vorstandswahl ergaben sich wieder Veränderungen: Schriftführer und Kassier legten ihre Funktionen zurück.
Ihre Agenden wurden von Josef Nentwich (Schriftführer) und Johann Nather (Kassier) übernommen.

1955 wurde Leopold Varecha zum Kapellmeister gewählt, nachdem auch Alois Makoschitz sein Amt zur Verfügung gestellt hatte.
In den nun folgenden Jahren konnte der Musikverein an den meisten Wertungsspielen teilnehmen, und im Jahre 1956 wurden einige Musiker mit dem Ehrenzeichen "`25 Jahre Blasmusik`" ausgezeichnet.

1958 wurde wieder ein neuer Obmann gewählt, und der Vorstand des Vereins setzte sich nun wie folgt zusammen:

Obmann:: Franz Kralik
Kapellmeister:: Leopold Varecha
Kassier:: Johann Nather

Die Vereinsleitung hatte es zu dieser Zeit schwer, die Musiker zusammenzuhalten.
Es gelang aber immer -- wenn auch mit Mühe -- den Verpflichtungen in Kirche und Gemeinde gerecht zu werden.
 
