---
title: "1960-1970"
date: 2018-10-14T22:22:57Z
draft: false
---
= 1960 -- 1970

Die finanzielle Lage erlaubte es nun, die Musiker neu einzukleiden, und so wurden 1960 die blauen Uniformen mit Kappen entworfen.
Die neue Kleidung war auch wieder ein neuer Ansporn, beim Musikverein tätig zu sein.
Bei der Wahl des Vorstandes im Jahre 1962 ergab sich folgende Besetzung der Funktionen:

Obmann:: Josef Nentwich
Kapellmeister:: Franz Haan
Kassier:: Franz Orth

Jetzt erhielt der Verein nach langer Zeit auch wieder Verstärkung durch Musikernachwuchs aus dem Ort.
1964 wurde die Obmannstelle mit Rudolf Neumann besetzt, und als Kapellmeister wurde Gottlieb Ostadal engagiert.

Es wurde beschlossen, von hoher Stimmung (Militär Stimmung - Höhe des Kammertones a^1^: 921,7 Schwingungen) auf Normalstimmung (Höhe des Kammertones a^1^: 870 Schwingungen) umzustellen, was nur mit beträchtlichen finanziellen Auslagen bewältigt werden konnte.
Der Wechsel zur Normalstimmung wurde vom Blasmusikverband für alle Mitgliedskapellen angeordnet, um mit einheitlicher Stimmung bei Großveranstaltungen gemeinsam musizieren zu können.

Nach harter Probenarbeit konnte der Musikverein Leopoldsdorf im Juni 1966 am Bezirksmusikfest in Dürnkrut teilnehmen.
1967 veranstaltete der Verein mit sehr großem Erfolg ein Bezirksmusikfest in Leopoldsdorf, das viele Besucher anzog.
Ein Jahr später kehrte der altbewährte Kapellmeister Alois Makoschitz wieder zu unserem Verein zurück, und im gleichen Jahr wurden die Musiker mit neuer Vereinskleidung ausgestattet.
