---
title: "1976-1980"
date: 2018-10-14T22:22:57Z
draft: false
---
= 1976 -- 1980

Vom 17. -- 19. September 1976 feierte der Musikverein Leopoldsdorf sein 50- jähriges Jubiläum.
Die Festlichkeiten begannen am Freitag mit einer Kranzniederlegung beim Kriegerdenkmal.
Das vorgesehene Platzkonzert konnte allerdings wegen Schlechtwetters nicht abgehalten werden.
Am Samstag fand eine Festsitzung im Vereinslokal Gottfried Schipitz unter Einbeziehung der Öffentlichkeit statt.
Bei dieser Festsitzung wurden einige Musiker mit Ehrenmedaillen geehrt.

Es waren dies:

mit der Ehrenmedaille in Bronze für 15 Jahre aktive Tätigkeit:: Heinrich Moskwyn, Felix Nentwich, Walter Nather
mit der Ehrenmedaille in Silber für 25 Jahre aktive Tätigkeit:: Johann Nather, Josef Sifkovits
das Ehrenzeichen für eifrige und ersprießliche Tätigkeit erhielten:: Johann Nather, Josef Nentwich, Rudolf Neumann, Franz Orth, sen., Josef Sifkovits

Der Musikverein ließ auch Vereinsabzeichen in Gold, Silber und Bronze anfertigen, die an folgende Musiker vergeben wurden:

in Silber (für verdiente, nicht mehr aktive Mitglieder):: Leopold Varecha, Karl Ivanics, Anton Ivanics, Adolf Sifkovits, Franz Kralik, Anton Buril, Karl Prybil, Otto Zoubek, Leopold Zoubek
in Bronze (für aktive Musiker):: Johann Brantner, Ferdinand Edinger, Günther Edinger, Günther Krammel, Christian Jandrisevits, Walter Nather, Felix Nentwich, Adolf Sifkovits, jun., Rudolf Steiner, Franz Orth, jun., Josef Zens
in Silber (für aktive Musiker):: Alois Makoschitz, Heinrich Moskwyn, Johann Nather, Josef Nentwich, Rudolf Neumann, Franz Orth, sen., Leopold Petrus, Alois Pytlik, Josef Sifkovits, Heinrich Zak

Die silberne Ehrennadel wurde an Gottfried Schipitz verliehen.
Zu der Festsitzung waren auch der Nachbarmusikverein Breitstetten und der Männergesangsverein Leopoldsdorf geladen, die die Feier musikalisch umrahmten.

Am Sonntag, den 19. September begannen die Feierlichkeiten mit einem Weckruf, wobei wir auch unsere neue Tracht der gesamten Bevölkerung vorstellen konnten.
Danach begrüßten wir auf dem Rathausplatz unsere Gastkapelle, die Jugendkapelle aus Mooskirchen.
Nach der Begrüßung wurde Aufstellung gemacht, und beide Kapellen marschierten zum Schulpark, wo der Festgottesdienst abgehalten wurde.
Die Mooskirchner spielten die Deutsche Messe von Franz Schubert unter der Leitung von Kapellmeister Franz Reischl.
Dechant Polen zelebrierte die hl. Messe und würdigte die Musik in besonderer Weise, wobei er ihre Wichtigkeit für das Leben der Menschen hervorhob.
Anschließend weihte Dechant Polen unsere neue Tracht.
Nach dem Gottesdienst marschierten beide Kapellen zum Vereinsgasthaus Schipitz, wo die Jugendkapelle Mooskirchen zum Frühschoppen aufspielte.
Danach gab es für die Mitglieder beider Kapellen ein Mittagessen, und nach einem gemütlichen Beisammensein wurde die Gastkapelle mit einer Fahrt in den Safaripark Gänserndorf verabschiedet.

Die Verbindung zur Mooskirchner Jugendkapelle wurde weiterhin gepflegt, und wir konnten die Musiker aus der Steiermark am 22.
und 23. August 1979 anlässlich der Rosenschau der Firma Grumer wieder bei uns in Leopoldsdorf begrüßen.
Es gab unter anderem ein Platzkonzert, ein Festkonzert, und eine Feldmesse mit anschließendem Frühschoppen.
