---
title: "1980-1990"
date: 2018-10-14T22:22:57Z
draft: false
---
= 1980 -- 1990

Am 5. Oktober 1980 wurde dann unser Verein zum 10- jährigen Jubiläum der Jugendkapelle nach Mooskirchen eingeladen.
Bei dieser Veranstaltung kamen 20 Blaskapellen mit über 500 Musikern zusammen.
Unserem Kapellmeister wurde die Ehre zuteil, beim Monsterkonzert einen Marsch zu dirigieren.
Doch kurz, nachdem er das Podium verlassen hatte, brach Alois Makoschitz zusammen und starb an den Folgen eines Herzinfarkts.
Dieses tragische Ereignis überschattete die Feierlichkeiten in Mooskirchen.
Beim Begräbnis in Leopoldsdorf waren auch die Mooskirchner Musiker dabei.
Nun war für uns eine schwere Zeit angebrochen und die Suche nach einem neuen Kapellmeister begann.

Franz Ostadal übernahm diese Funktion und schon im ersten Jahr seiner Tätigkeit konnten wir wieder am Konzertwertungsspiel in Gänserndorf teilnehmen.
Der Musikverein spielte bei den Veranstaltungen in unserer Gemeinde und nahm am 5.
September 1982 am Landesmusikfest in Laa/Thaya, im Marschmusikblock mit den Vereinen aus Franzensdorf und Breitstetten teil.

In der Jahreshauptversammlung am 4.
März 1983 wurde über eine Änderung der Statuten, den Vereinsnamen betreffend, abgestimmt und diese auch beschlossen: Seither heißt der Verein Musikverein Leopoldsdorf (statt Arbeitermusikverein).
Dieser Antrag war einstimmig angenommen worden.

Am 17.2.1984 fand die erste Jahreshauptversammlung nach der Namensänderung statt, der Verein hatte in diesem Jahr 25 aktive Mitglieder.
Der neue Vorstand setzte sich wie folgt zusammen:

Obmann:: Johann Nather
Obmann-Stv.:: Josef Sifkovits
Schriftführer:: Alois Pytlik
Kassier:: Felix Nentwich sen.
Kassier-Stv.:: Heinrich Zak
Kapellmeister:: Franz Ostadal sen.
Kapellmeister-Stv.:: Franz Ostadal jun.
Instrumentenwart:: Leopold Petrus
Notenarchivar:: Roman Hörler
Kontrolle:: Rudolf Steiner, Herbert Raming

Neben dem Frühlingskonzert am 4. Mai 1984 spielte der Verein bei der Konzertwertung in Hohenau und beim Musikfest in Haringsee.
Am 11. April 1986 veranstaltete der MV Leopoldsdorf ein Jubiläumskonzert zum 60- jährigen Bestand.
Bei diesem Konzert wurden auch einige verdiente Musiker ausgezeichnet:

Bronze (15 Jahre aktive Mitgliedschaft):: Rudolf Steiner; Franz Plank, Franz Ostadal, jun.
Silber (für 25 Jahre aktive Mitgliedschaft):: Heinrich Moskwyn, Felix Nentwich, Herbert Raming
Gold (für 40 Jahre aktive Mitgliedschaft):: Josef Nentwich, Leopold Petrus, Alois Pytlik, Franz Ostadal, sen., Heinrich Zak

Die silberne Ehrennadel für die Förderung der Volksmusik erhielten Altbürgermeister Ludwig Vymyslicky, Josef Harlacher und Johann Nather, zum Ehrenmitglied des Vereins wurde Josef Sifkovits ernannt.

Am 5. Juni 1988 wurde Leopoldsdorf zur Marktgemeinde erhoben und die Musikkapelle wurde mit hellblauen Uniformen ausgestattet.
(Die passenden Mäntel wurden im Jahr 1989 angeschafft.) Das Fest anlässlich der Markterhebung dauerte 4 Tage und wurde mit einem Festkonzert des Musikvereins begonnen.
Auch bei der Ausstellung "`Unsere Gemeinde einst und jetzt`" spielte eine Bläsergruppe aus unserem Verein.
Der eigentliche Festakt am 5. Juni wurde mit einer Feldmesse eingeleitet, bei dem die Musikvereine aus Leopoldsdorf und Breitstetten spielten.
Danach gab es einen Frühschoppen auf dem Rathausplatz.

Im Jahr 1989 feierte die Freiwillige Feuerwehr Leopoldsdorf ihr 100- jähriges Bestehen, für die musikalische Umrahmung sorgte unser Musikverein.
Der Tag der Blasmusik wurde traditionsgemäß im September abgehalten, und nach der Feldmesse wurden Rudolf Steiner mit der Silbernen Ehrenmedaille (25 Jahre) und Johann Nather mit der Goldenen Ehrenmedaille (40 Jahre) ausgezeichnet.

Bei der Hauptversammlung 1990 wurde ein neuer Vorstand gewählt:

Obmann:: Heinrich Moskwyn
{empty}1. Obmann-Stv.:: Roman Hörler
{empty}2. Obmann-Stv.:: Mario Kosour
Kassier:: Felix Nentwich sen.
Kassier-Stv.:: Heinrich Zak
Schriftführer:: Felix Nentwich jun.
Kontrolle:: Herbert Raming, Johann Nather
