---
title: "1990-1994"
date: 2018-10-14T22:22:57Z
draft: false
---
= 1990 -- 1994

Seit 1992 war Felix Nentwich, jun. Kapellmeister des Leopoldsdorfer Musikvereins.
Von Anfang an setzte er sich zum Ziel, die musikalische Qualität des Vereins noch zu steigern.
Ein wichtiger Schritt dazu war auch seine Ausbildung zum Kapellmeister, die er seit dem Jahre 1994 beim NÖ Blasmusikverband absolvierte.
Aber nicht nur der Kapellmeister arbeitete an sich, auch die jungen Musiker/innen absolvierten Kurse und Seminare und konnten dafür Leistungsabzeichen für Jungmusiker in Empfang nehmen.

In den letzten Jahren hatte unser Musikverein regelmäßig an den Konzert- und Marschmusikbewertungen im Bezirk teilgenommen und konnte jeweils mit sehr gutem oder sogar ausgezeichnetem Erfolg nach Hause fahren.
Auch an den Kammermusikwettbewerben nahmen seit einigen Jahren Ensembles, bestehend aus Mitgliedern des MV Leopoldsdorf, teil.
Alle diese Aktivitäten zeugten von dem Bemühen der Vereinsleitung und der Musiker, sich musikalisch weiterzubilden, und dass wir diese Bewertungen nicht zu scheuen brauchen, davon konnte sich die Bevölkerung in den letzten Jahren bei diversen Veranstaltungen überzeugen.

So wurde auch die Tradition eines Krampuskonzertes wieder aufgenommen, im Rahmen dessen wir Musikstücke aus fast allen Sparten des Blasmusikrepertoires dem Publikum darbieten konnten.
Besonders erfreulich war es, dass die Jugend von Leopoldsdorf seit einigen Jahren Gelegenheit hatte im Ort eine Musikschule zu besuchen, und dieses Angebot wurde gerne genützt.
