---
title: "1996"
date: 2018-10-14T22:22:57Z
draft: false
---
= 1996

Im Jahr 1996 feierte unser Verein mit einem wunderschönen, groß angelegten, 3-tägigen Fest in der Scheit-Halle sein 70-jähriges Bestandsjubiläum: Am Freitag, den 17.
Mai sorgte die „Blaskapelle Makos“ für musikalische Unterhaltung vom Feinsten; Samstag, den 18.
Mai spielten die „Weltenbummler“ für uns auf.
Der Höhepunkt des Festes jedoch war mit Sicherheit das Bezirksmusikfest am Sonntag, den 19.
Mai, an dem über 20 Kapellen ihr marschmusikalisches Können präsentierten.
Unter ihnen auch unsere Partnerkapelle aus Mooskirchen, die für uns eine großartige Feldmesse, und anschließend den Frühschoppen gestalteten.

Im selben Jahr konnten wir auch den alljährlichen Kammermusik- Wettbewerb am 30.11.
in Leopoldsdorf abhalten, an dem über 25 Gruppen aus dem Bezirk teilnahmen.

Beim traditionellen Krampuskonzert wurden viele Ehrungen vorgenommen.
Es waren dies:

Ehrenmedaille in Bronze für 15 Jahre aktive Tätigkeit:: Herbert Raming
Ehrenmedaille in Gold für 40 Jahre aktive Tätigkeit:: Heribert Mokesch, Johann Schöner
Ehrenmedaille in Gold für 50 Jahre aktive Tätigkeit und Ernennung zum Ehrenmitglied des MV Leopoldsdorf:: Josef Nentwich

Außerdem hat der Verein beschlossen, vereinsinterne Mitgliedsabzeichen einzuführen:

Mitgliedsabzeichen in Bronze:: alle aktiven Vereinsmitglieder
Mitgliedsabzeichen in Silber für 20 Jahre Vereinsmitgliedschaft:: Rudolf Steiner, Felix Nentwich jun.
Mitgliedsabzeichen in Gold für 35 Jahre Vereinsmitgliedschaft:: Felix Nentwich sen.
Mitgliedsabzeichen in Gold für 35 Jahre Vereinsmitgliedschaft und Ernennung zum Ehrenmitglied des MV Leopoldsdorf:: Heinrich Moskwyn
Funktionärs-Ehrennadel in Gold und Ernennung zum Ehrenobmann des MVL:: Johann Nather
Fördernadel in Silber des NÖ- Blasmusikverbandes:: Bgm.Peter Nagel, Johann Scheit
