---
title: "1998"
date: 2018-10-14T22:22:57Z
draft: false
layout: "single"
---
= 1998

Waren 1997 noch etwa 16 Musiker/innen in der Probe, so lag der Probenbesuchsdurchschnitt 1998 bereits bei 20 Musiker/innen.
Außerdem konnten wir erstmals einen Mitgliederstand von 26 vorweisen, was nicht zuletzt Verdienst unserer qualitativ hochwertigen Musikschule war.

Überdies wurde 1998 ein neuer Vorstand gewählt:

Obmann und Kpm.-Stv.:: Roman Hörler
Obmann-Stv.:: Johann Schöner
Kapellmeister:: Felix Nentwich jun.
Kassier:: Wilhelm Herok
Kassier Stv.:: Nentwich Felix sen.
Schriftführer:: Clemens Nagel
Schriftführer-Stv.:: Barbara Schwarz
Beisitzer:: Johann Nather, Heribert Mokesch

Ein Schwerpunkt dieses Jahres war mit Sicherheit die Eröffnung des neuen Musikheimes.
Wir hatten uns nämlich mit großem finanziellem Aufwand eine ausgezeichnete akustische Inneneinrichtung geleistet.
Davon jedenfalls konnten sich alle Besucher der Festmesse überzeugen, da diese auf Grund des Schlechtwetters im neuen Musikheim stattfand.
Nach einem Frühschoppen unterhielt am Nachmittag die Blaskapelle Marchfeld die Gäste.

Im Zuge des Festaktes wurden einige Ehrungen vorgenommen:

Ehrenmedaille in Bronze für 15 Jahre aktive Tätigkeit:: Roman Hörler
Das Musikheim-Verdienstabzeichen für unentgeltlich geleistete Arbeitsstunden erhielten:
In Bronze:: Roman Hörler, Barbara Schwarz, Heribert Mokesch, Hannelore Steiner
In Silber:: Felix Nentwich sen., Johann Nather
In Gold:: Rudolf Steiner, Felix Nentwich jun.

Um unser neues Erscheinungsbild zu vervollständigen, entschlossen wir uns im Sommer, eine neue Vereinstracht anzukaufen.
Da wir finanziell durch den Musikheimbau sehr belastet waren, starteten wir eine große Bausteinlosaktion, die mit einer Riesen-Tombola zum Krampuskonzert endete, bei dem auch gleich unsere neue Tracht feierlich der Öffentlichkeit präsentiert werden konnten.
