---
title: "2001"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2001

Im Jahr 2001 begingen wir unser 75-jähriges Bestandsjubiläum mit einer zweitägigen Feier im Garten des Musikheimes.
Dafür hatte sich der Musikverein in Eigenregie ein Zeltgestänge gebaut und aufgestellt, das nun Festivitäten aller Art bei jedem Wetter im Musikheimgarten zuließ.

Anfang des Jahres erhielt der Verein den Ehrenpreis in Bronze des Landeshauptmannes für seine fortwährend konstanten, ausgezeichneten Leistungen bei Konzertwertungsspielen, Marschmusikwertungen, Kammermusikwertungen und Weisenblasen.
Unser Kapellmeister erhielt aus diesem Grund auch die Dirigentennadel in Bronze.

Dank seiner hervorragenden Musikschulleitung konnten zahlreiche junge Musiker/innen in den letzten Jahren erfolgreich in den Verein integriert werden.
So zählen wir heute bereits 34 aktive Vereinsmitglieder.

Unser Kapellmeister gestaltete zu seinem 10-jährigen Jubiläum überdies eine Fest-Probe, genau zu dem Datum, an dem er vor 10 Jahren die Probenarbeit mit dem Verein aufnahm, zu der alle ehemaligen Vereinsmitglieder, Ehrenmitglieder, sowie Ehrengäste eingeladen waren.
Felix Nentwich ließ die letzten 10 Krampuskonzerte musikalisch und literarisch Revue passieren und veranstaltete ein Wunschkonzert für die Gäste.

Mit dem Kirchenkonzert 2001, gewidmet unserem scheidenden Pfarrer Ernst Pankl, hatten die Leopoldsdorfer kulturschaffenden Vereine (Musikverein, Männergesangverein, Kirchenchor) eine bislang verborgen gebliebene Quelle neuer Klangfarben und Harmonien erschlossen, die zu einem gewaltigen Klangerlebnis wurde.

Beim Krampuskonzert wurden folgende verdiente Musiker und Vereinsförderer geehrt:

Ehrenmedaille in Gold für 40 Jahre aktive Tätigkeit:: Felix Nentwich sen.
Silbernes Ehrenzeichen für eifrige und ersprießliche Tätigkeit um das Blasmusikwesen in NÖ:: Kpm.
Felix Nentwich  Förderernadel in Silber:: Kurt Schwarz
