---
title: "2002"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2002

Im Jahr 2002 kaufte der Musikverein Leopoldsdorf für sein Zeltgestänge eine große, einheitliche weiße Dachplane, um beim alljährlichen Dämmerschoppen nicht "`im Regen zu stehen`".
Dafür fiel aber die Marschmusikbewertung in Staatz (Mistelbach), an der wir wieder gemeinsam mit der Ortsmusik Franzensdorf teilnehmen wollten sprichwörtlich ins Wasser.
Der MV nahm in Mistelbach teil, da wir zu der gleichen Zeit, als die Bewertung in unserem Bezirk gewesen wäre, einen Vereinsausflug mit Konzert in Gloggnitz gaben, zu dem wir vom Wanderwallfahrtsverein samt ehem.
Pfarrer Ernst Pankl und der Stadtkapelle Gloggnitz eingeladen waren.
An diesem wunderschönen Ausflug nahmen sehr viele MusikerInnen samt Angehörigen und Gäste teil.

Bei der Konzertwertung in diesem Jahr gelang unserem Verein allerdings eine Sensation.
(Zitat aus der Gemeindezeitung):  *Ein Meilenstein in der Vereinsgeschichte!*  Zum ersten Mal seit dem Bestehen des Vereines hatten wir unter der Leitung von Kpm.
Felix Nentwich erreicht, was zuvor noch niemand mit dem Musikverein erreicht hat: Am 27.
April 2002 traten wir bei der Konzertwertung in Matzen in der Schwierigkeitsstufe C (Oberstufe), mit den Stücken Jazz Walz No.
1 und Lacrimosa an, und erreichten einen *AUSGEZEICHNETEN ERFOLG*!  _Die harte Proben- und Nachwuchsarbeit hat sich gelohnt!_  Das Kirchenkonzert in diesem Jahr bestritten wir alleine, ohne MGV und Kirchenchor.
Die moderne Literatur fand bei dem großen Publikum in der akustisch wunderbaren Kirche guten Anklang.

Für die Verbesserung des innervereinlichen Sozialgefüges wurde vom Vorstand ein Tischfussball-Gerät angekauft, das sich sofort größter Beliebtheit erfreute, und zur Veranstaltung eines großen vereinsinternen Turniers (Tischfussball, Dart, Tischtennis) nach Weihnachten führte.

Beim Krampuskonzert wurden folgende verdiente Musiker geehrt:

Ehrenmedaille in Silber für 25 Jahre aktive Tätigkeit:: Kpm. Felix Nentwich

Darüber hinaus wurden zwei verdiente Vereinsmitglieder in allen Ehren aus ihrer aktiven Mitgliedschaft in den "`Musikerruhestand`" verabschiedet.
Ihnen wurde überdies die Ehrenmitgliedschaft des Musikvereines verliehen: Felix Nentwich sen., Heribert Mokesch
