---
title: "2003"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2003

Im Jahr 2003 wählte der Verein einen neuen Vorstand:

Obmann:: Johann Schöner
Obmann-Stv.:: Wilhelm Herok
Kassier:: Dieter Hauer
Kassier- Stv.:: Felix Nentwich
Schriftführer:: Clemens Nagel
Schriftf.-Stv.:: Andreas Niedermayer
Archivar:: Benjamin Golec
Archivar- Stv.:: Gerhard Kohlhuber
Jugendreferent:: Andreas Bintinger
Jugendreferent-Stv.:: Paul Ritschl

Damit hatte der Verein zum ersten Mal in seiner Geschichte Jugendreferenten.
Diese Maßnahme war als Zeichen für den hohen Anteil an jungen MusikerInnen zu verstehen, denen der Verein eine gewichtige Stimme im Vorstand einräumen wollte.

Im Frühjahr bereiteten wir den Ankauf von Seitenwänden für unser Veranstaltungszelt vor.
Mit Hilfe von Sponsoren, die Werbeflächen auf den Innenwänden erwarben, wurden diese Seitenwände finanziert.
So hatten wir auch bei schlechterem Wetter eine gute Möglichkeit, unsere Eigenveranstaltungen im eigenen Garten durchzuführen.

Nachdem der Musikverein im Vorjahr gemeinsam mit dem Kirchenchor und dem Männergesangverein ein Konzert in der Kirche veranstaltet hatte, wurde diese Idee weitergeführt.
Da unser neuer Pfarrer Kollmann nicht wollte, dass das Konzert erneut in der Kirche stattfindet, fand es unter dem Titel "`Konzert im April`" in der Sporthalle statt.
Mit Stücken wie "`Der Bettelstudent`", "`Vivaldi’s Winter`", "`Festival in Silber`" begeisterten wir das Publikum.
Als Höhepunkt wurde der "`Hallelujah Chorus`" aus Messias von G.F.Händel on allen Beteiligten aufgeführt.

Zum Konzertwertungsspiel in Zistersdorf spielten wir "`WOSN`" und "`Festival in Silber`".
Mit 90,83 Punkten verfehlten wir nur ganz knapp eine Auszeichnung in der Stufe C.
Beim Weisenblasen im Juni in Matzen waren wir mit 3 Gruppen (Dominik Hauer und Markus Nentwich, Herbert Preyer und Felix Nentwich, Matthias Kohlhuber und Christian Martins) vertreten.
Unser Dämmerschoppen fand am 31.
Mai 2003 statt, als Gastkapelle hatten wir die Stadtkapelle Gloggnitz zu Besuch, da unser Pfarrer Ernst Pankl dorthin übersiedelt war.
Im Anschluss an die Blasmusik unterhielten uns "`Gery und Sandra`".

Am 15. Juni waren wir in Deutsch Wagram beim Jubiläumsfest des BLO mit einer Marschvorführung vertreten.
Bei der Marschmusikbewertung in Neusiedl/Zaya erreichten wir gemeinsam mit der OM Franzensdorf mit der Kürfigur "`Wikingerschiff`" einen ausgezeichneten Erfolg in der Stufe E.
Am 15. September 2003 führte uns ein Vereinsausflug nach Gloggnitz, wo wir auch ein Unterhaltungskonzert bestritten.
Zum Kammermusikwettbewerb in Obersulz traten 4 Gruppen unseres Vereins an.

Als neue Mitglieder begrüßten wir Simone Bintinger, Wolfgang Prinzjakowitsch und Daniela Weber im Verein.
Letztgenannte blieb aus beruflichen Gründen leider nur bis zum Krampuskonzert bei uns.
Wolfgang Prinzjakowitsch erstellte für uns erstmals eine Homepage, die unter http://www.mvl.at veröffentlicht wurde.

Beim Krampuskonzert erhielt Rudolf Steiner vom NÖBV die Ehrenmedaille in Gold für mindestens 40-jährige aktive Musikausübung.
Roman Hörler erhielt das Vereinsabzeichen in Silber für 20-jährige Treue zu unserem Verein.
Dominik Hauer spielte beim Krampuskonzert das Concertino für Posaune und Blasorchester von Sachse als Solokonzert für das JMLA in Gold und erreicht damit einen sehr guten Erfolg.
Des Weiteren erfreuten unter anderem Stücke wie West Side Story, Miss Marple Theme oder Wiener Operettenklassiker das Publikum.
