---
title: "2004"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2004

Unser Obmann Johann Schöner beendete aus gesundheitlichen Gründen seine musikalische Karriere und legte in diesem Zusammenhang auch sein Amt als Obmann zurück.
Bei der Wahl am 13. Februar 2004 wurde folgender Vorstand einstimmig gewählt:

Obmann:: Wilhelm Herok
Obmann-Stv.:: Clemens Nagel
Kapellmeister:: Felix Nentwich
Kpm-Stv.:: Clemens Nagel
Kassier:: Dieter Hauer
Kassier-Stv.:: Felix Nentwich
Schriftführer:: Wolfgang Prinzjakowitsch
Schriftführer-Stv.:: Andreas Niedermayer
Jugendreferent:: Andreas Bintinger
Jugendreferent-Stv.:: Paul Ritschl
Archivar:: Benjamin Golec
Archivar-Stv:: Alexandra Häusler

Am 28. Februar mussten wir leider unseren langjährigen Musikkollegen Ehrenmitglied Heribert Mokesch zu Grabe tragen.

Am 24. April erreichten wir beim Konzertwertungsspiel in Hohenruppersdorf mit den Stücken Marche Dramatique und Sinfonie in Pop 91,83 Punkte und somit die dritthöchste Wertung in dieser Stufe.

Als Würdigung unserer Leistungen bei Veranstaltungen des NÖBV erhielten wir von Landeshauptmann Dr.
Erwin Pröll den Ehrenpreis in Bronze für 700 erreichte Punkte bei Wertungsspielen.
Am 8. Mai spielten wir beim Damenfußball EM-Qualifikationsspiel Österreich - Slowakei die Nationalhymnen der beiden Mannschaften in unserem Waldstadion.

Erstmals veranstalteten wir die "`Nacht der Filmmusik`" als Open Air Konzert gemeinsam mit dem BLO der MS Deutsch Wagram am Platz vor der Volksschule.
Dabei spielten wir gemeinsam bekannte Filmmelodien wie "`Das Boot`", "`Das Dschungelbuch`", "`James Bond 007`", "`Pearl Harbour`" etc.
dazu wurden die passenden Filmszenen auf eine Großbildleinwand projiziert.
Durch eine professionelle Beleuchtungsfirma wurden auch die über 60 Musiker/innen ins richtige Licht gerückt.
Mit dieser gelungenen Veranstaltung konnten wir das Publikum nicht nur in Leopoldsdorf, sondern auch in Deutsch Wagram mehr als begeistern.

Für einige Turbulenzen sorgte der Umstand, dass wir auf Grund der Verkettung von unglücklichen Umständen und Missverständnissen nicht an der Fronleichnamsprozession teilnahmen.
Nach einer Aussprache mit dem Pfarrer und dem Pfarrgemeinderat wurde diese traurige Situation bereinigt.

Bei unserem traditionellen Dämmerschoppen im Juni hatten wir den MV Breitstetten zu Gast.
Ebenfalls im Juni führte uns eine Einladung zu einem zweitägigen Ausflug nach Sered in der Slowakei, wo wir am dortigen Kirtag für musikalische Unterhaltung sorgten.
Beim Musikfest in Haringsee waren wir ebenfalls vertreten.
Im August spielten wir für den MV Breitstetten anlässlich seines 80-Jahr Jubiläums zum Frühschoppen auf.

Zum Tag der Blasmusik spielten wir erstmals am Freitag unter dem Motto "`Blasmusik vorm Haus`" in der Fasangasse, wo wir auch die AnrainerInnen mit Getränken bewirteten.
Bei der Marschmusikbewertung in Jedenspeigen erreichten wir in der Stufe E mit der Kürfigur "`Schnecke`" mit 89,5 Punkten einen sehr guten Erfolg.

Am 15. September 2004 feierte unser Bürgermeister mit allen Vereinen in Leopoldsdorf sein 15-jähriges Amtsjubiläum.
Unser Musikverein schenkte ihm dafür den Bgm.
Peter Nagel Marsch, den Kpm.
Felix Nentwich eigens für diesen Anlass komponiert hatte.
Peter Nagel hatte an dieser Überraschung sehr viel Freude.

Beim Kammermusikwettbewerb war unser Verein mit 4 Gruppen vertreten.
Der Musikverein beschloss, ein Vereinslogo zu entwerfen.
Unser Obmann Wilhelm Herok gewann den dazu veranstalteten Logo-Wettbewerb und sein Entwurf sollte in Zukunft als offizielles Logo unseres Vereins fungieren.

Auch über Musikernachwuchs der offiziell beim Krampuskonzert am 4.
Dezember mit dem Vereinsabzeichen aufgenommen wurde, konnten wir uns freuen.
Magdalena Zak und Alexandra Häusler erweiterten das Holzregister, mit David Leitner bekamen auch die Flügelhornisten einen neuen Kollegen.
Unser ehemaliger Obmann Johann Schöner wurde offiziell zum Ehrenmitglied ernannt.
Im Konzertprogramm fanden sich Stücke wie "`Carmen`", "`Hymn of the Highlands`", "`Batman`", "`Abba Gold`" und vieles mehr.
