---
title: "2005"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2005

Am 16. April schafften wir beim Konzertwertungsspiel in Prottes mit den Stücken "`Tricondo`" und "`Wings of Freedom`" 93 Punkte in der Stufe C.
Das war die höchste Punktezahl, die wir bis dato je erreichen konnten.
Am 21. April lud der Musikverein zum 2. Mal zur "`Nacht der Filmmusik`" ein.
Auf dem Programm standen tolle Melodien aus bekannten Filmen wie "`Der mit dem Wolf tanzt`", "`Gladiator`", "`Batman`", "`Indiana Jones`" und vieles mehr.
Das Projekt wurde -- wie im Vorjahr -- mit dem BLO der MS Deutsch Wagram veranstaltet und zwei Wochen später auch dort aufgeführt.
Unser Dämmerschoppen fand erstmals unter dem Titel "`Sommernachtsfest`" statt, nach einem Dämmerschoppen des MV sorgt die Band "`Two for You`" mit Tanzmusik für gute Stimmung und Unterhaltung.
Beim Weisenblasen in der Nexinger Schweiz nahmen zwei Gruppen unseres Vereins teil.
Zum Tag der Blasmusik spielten wir Anfang September erneut unter dem Motto "`Blasmusik vorm Haus`" in der Dr.
Richard Skene Siedlung auf, die traditionelle Messe mit Agape fand in unserem Musikheim statt.

Bei der Marschmusikbewertung in Prottes erreichten wir mit der Showfigur 80er 92 Punkte und somit einen ausgezeichneten Erfolg in der Stufe E.
Beim Wettbewerb "`Spiel in kleinen Gruppen`" waren wir ebenfalls mit einem Trio vertreten.

Der Höhepunkt des Krampuskonzerts war der Walzer "`Geschichten aus dem Wienerwald`" mit Zithersolo, aber auch die Solisten Mario Nentwich mit "`Xylo Classics`" und Dominik Hauer mit der "`Bayrischen Polka`" begeisterten das Publikum.
Reinhard Stöckl (Bariton) und Raffael Nagel (Waldhorn) wurden in den Verein aufgenommen, Rudolf Steiner wurde aus gesundheitlichen Gründen mit dem Marsch "`Unter dem Doppeladler`" als aktiver Musiker verabschiedet und zum Ehrenmitglied ernannt.

Beim ersten niederösterreichischen Schlagwerkwettbewerb gingen Mario Nentwich und Jan Michael Auer mit 95 Punkten als Sieger hervor, sie erhielten dafür auch im Jahr darauf die Ehrung "`Dank und Anerkennung`" der Marktgemeinde Leopoldsdorf.
Mit ausschließlich ausgezeichneten Erfolgen bei allen Wettbewerben zählte das Jahr 2005 zu einem der musikalisch erfolgreichsten der Vereinsgeschichte.
