---
title: "2006"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2006

Bei der Generalversammlung wurden folgende Vorstandsposten neu gewählt: Carina Vymyslicky wurde neue Schriftführerin und Pressereferentin, ihr Stellvertreter wurde Paul Ritschl.
Des Weiteren wurden Katharina Domitzi und Matthias Kohlhuber die neuen Vereinsjugendrefernten, alle anderen Positionen wurden bestätigt.

Am 22. April schaffte der Musikverein Leopoldsdorf bei der Konzertmusikbewertung in Gänserndorf mit den Stücken "`Ars Vivendi`" und "`Rhapsodie Provencale`" 92,83 Punkte in der Stufe C und somit das beste Ergebnis vom ganzen Bezirk in dieser Stufe.
Der Jungmusiker Arthur Knaus hatte gleichzeitig seinen ersten Auftritt als Trompeter des Vereins.

Im April wurde die erste Musik CD des Vereins mit dem Titel "`MV Leopoldsdorf -- 80 Jahre und kein bisschen leise`" produziert.
Die Aufnahme erfolgte an zwei Wochenenden in unserem Musikheim, die Aufnahmeleitung hatte Prof.
Franz Kastner inne, für die richtige Tontechnik war Josef Plott mit seinem mobilen Tonstudio zuständig.
Die CD bot ein buntes Musikprogramm und dokumentierte einen Ausschnitt unseres aktuellen Repertoires mit allen Stilrichtungen.

Ende Mai verstarb unser langjähriges Vereins- und Ehrenmitglied Rudolf Steiner, den wir mit allen Ehren in Obersiebenbrunn zu Grabe geleiteten.

Der Höhepunkt des Jahres war unser Fest anlässlich 80 Jahre MV Leopoldsdorf.
Vom 9. -- 11. Juni wurde ein dreitägiges Fest organisiert, um dieses Jubiläum auch gebührend zu feiern.
Am Freitag startete das Fest mit einer Übertragung des Eröffnungsspiels der Fußball WM in Deutschland auf Großbildleinwand.
Anschließend wurde bei einer MP3-Party mit DJ Body und Karaoke-Singen in unserem Vereinszelt gefeiert.
Am Samstag begann das Fest nachmittags mit der Bezirksveranstaltung "`Weisenblasen`", wobei 5 Gruppen unseres Vereins sehr erfolgreich teilnehmen.
Am Abend unterhielt die "`Blasmusik Bohemia`", unter Leitung unseres Vereinsmitglieds Reinhard Stöckl, mit Blasmusik der Spitzenklasse.
Der Sonntag stand unter dem Motto "`Bezirksblasmusikfest`": 12 Vereine zeigten im Waldstadion bei Marschvorführungen und bei einem Großkonzert ihr Können.
Unser Verein bildete als Showfigur einen 80er, bei der anschließenden musikalischen Einlage bekam unser Stabführer Clemens Nagel vom Schiedsrichter Erich Fischer die gelb-rote Karte, sodass wir den Fußballplatz verlassen mussten.
Der Ausklang fand in unserem Vereinszelt statt.
Zuerst unterhielt uns die Gastkapelle aus Pillichsdorf, anschließend präsentierte unser Musikverein einige Stücke der CD live, zum Abschluss spielte die Big Band "`The Big Bang`", die Kapellmeister Felix Nentwich leitet.
Anlässlich dieses Jubiläumsfestes wurde auch erstmals eine Vereinszeitung herausgegeben.
Beim Tag der Blasmusik Anfang September konzertierten wir freitags in der Freiheitssiedlung vor dem "`400er`" Haus, am Sonntag zelebrierte der neue Pfarrer Robert Rys erstmals die heilige Messe in Leopoldsdorf.

Am 16. September erreichten wir bei der Marschmusikbewertung in Orth/Donau unter Stabführer Clemens Nagel mit 93 Punkten in der höchsten Stufe E das drittbeste Ergebnis aller Kapellen unseres Bezirks.
Als Showfigur präsentierten wir einen "`Südböhmischen Doppelkreis`", im Zuge dessen wir auch Rosamunde zum Besten gaben.
Traditionellerweise wurde das musikalische Jahr mit dem Krampuskonzert beendet.
Im vollen Saal des Gh. List wurden Blasmusikhighlights wie "`Fate of the Gods`", "`Serenade von Bourgeois`", "`Concerto per Clarinetto`" (Solistin Alexandra Häusler), "`Orpheus in der Unterwelt`", "`Jungle`" und mehr zum Besten gegeben.
Erstmals hatten wir auch eine Oboe und eine Bassklarinette besetzt.

Arthur Knaus, Oliver Petschk und Sebastian Kukol wurden mit dem Vereinsabzeichen in Bronze offiziell in den Verein aufgenommen.
Wilhelm Herok und Clemens Nagel erhielten das Ehrenzeichen für eifrige und ersprießliche Tätigkeit für den NÖBV, Felix Nentwich wurde die Ehrennadel in Silber des NÖBV verliehen.
