---
title: "2007"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2007

Bei der Generalversammlung mit Neuwahlen wurde der Vorstand in seiner Zusammensetzung einstimmig wiedergewählt, nur Paul Ritschl (Studium in Salzburg) wurde durch Andreas Bintinger als Schriftführer--Stv.
ersetzt. Zusätzlich wurde Oliver Petschk als Beirat mit der Verantwortlichkeit für die Homepage in den Vorstand gewählt.

Im April spielten wir die Hymnen beim U18--Fußball--Ländermatch Österreich -- Slowakei.
Bei der Konzertmusikbewertung in Hohenau erreichten wir in der Stufe C mit den Stücken "`Virginia`" und "`Fate of the Gods`" 92,5 Punkte.
Beim anschließenden Heurigenbesuch in Mannersdorf wurde dieser Erfolg gebührend gefeiert, einige Musiker/innen verwöhnten das Publikum mit böhmischer Blasmusik.

Im Mai erhielt der Musikverein als einer der ersten Vereine des Bezirks feierlich den Ehrenpreis in Silber vom Landeshauptmann für 1400 erreichte Punkte bei NÖBV – Veranstaltungen verliehen.

Beim zweiten niederösterreichischen Schlagwerkwettbewerb gingen Mario Nentwich und Jan Michael Auer erneut als Sieger hervor und erhielten daraufhin bereits zum zweiten Mal die Ehrung "`Dank und Anerkennung`" der Marktgemeinde Leopoldsdorf verliehen.

Gemeinsam mit dem Blasorchester der Musikschule Deutsch Wagram luden wir am 9.
Juni erneut zur Nacht der Filmmusik am Platz vor der Volksschule, tags darauf fand erstmals ein Frühschoppen im Kulturhausgarten statt.
Am 25. August 2007 bestritt der Verein einen Gastauftritt in Pillichsdorf und spielte beim Musikheurigen in der Kellergasse auf.

Der Vereinsausflug am Samstag, den 15. September führte uns nach Krems, wo neben einer Besichtigung der Altstadt auch der Besuch des Karikaturmuseums anstand.
Danach erwartete uns in Türnitz die Sommerrodelbahn "`Eibl Jet`", es konnte aber auch eine Wanderung durch die Falkenschlucht unternommen werden.
Bevor wir unsere Heimreise antraten, kehrten wir noch zu einem gemütlichen Beisammensein bei Speis und Trank beim Mostheurigen Karner ein.

Beschlossen wurde das Arbeitsjahr mit dem 16. Krampuskonzert am 1. Dezember im Gasthaus List, im Zuge dessen Kpm.
Felix Nentwich mit dem Vereinsabzeichen in Gold, für eine mehr als 35--jährige Migliedschaft, ausgezeichnet wurde.
