---
title: "2008"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2008

Das Jahr 2008 begann wie gewohnt erfolgreich mit der Konzertmusikbewertung in Ebenthal.
Der Musikverein erreichte in der Schwierigkeitsstufe C mit den beiden Stücken "`Verwehte Blumen`" und "`Enjoy the Music`" 91,92 Punkte.

Im Rahmen der Festwochen zum 20-jährigen Jubiläum der Marktgemeinde war der Musikverein aktiv tätig: Zusammen mit dem Kirchenchor, dem Jugendblasorchester der Musikschule, dem Männergesangsverein und der Spielmusik veranstaltete er am 13.
April das Konzert im Frühling in der Sporthalle der Hauptschule.
Unser alljährlicher Frühschoppen am 1.
Juli stand ebenfalls im Zeichen dieser Festwochen.
Bürgermeister Peter Nagel führte in diesem feierlichen Rahmen den offiziellen Bieranstich des Leopoldsdorfer Festbräus durch.
Erstmals wurde der Musikverein durch unseren guten Freund Peter Janoch, dem Sänger der Blaskapelle Bohemia, gesanglich unterstützt.

Dank ihres großartigen Erfolgs im Jahr 2007 beim Niederösterreichischen Landeswettbewerb durften die Schlagzeuger Mario Nentwich und Jan Michael Auer als "`Duo Malletimpani`" in Feldkirch am Bundeswettbewerb teilnehmen.
Sie erreichten dabei den fünften Platz.

Obmann Wilhelm Herok absolvierte das zweijährige ÖBV-Seminar für Führungskräfte.

Den Tag der Blasmusik begingen wir am Freitag, den 5.
September mit einem Platzkonzert an der Wiener Straße, am 6.
September luden wir zur Hl.
Messe mit anschließender Agape vor der Kirche.

Am 20. September veranstalteten wir zum ersten Mal ein Sturmfest, das nicht wie geplant im Schubertparkt, sondern wetterbedingt im überdachten Kulturhausgarten stattfand.

Am 6. Dezember lud der Musikverein unter der Leitung von Kapellmeister Felix Nentwich und seinem Stellvertreter Clemens Nagel zum 17.
Mal zum traditionellen Krampuskonzert.
Das Repertoire reichte von klassischen Stücken wie etwa "`Chanson Napolitaine`" von Peter Ilijitsch Tschaikowsky oder "`Die diebische Elster`" von Gioachino Rossini über traditionelle Werke wie die "`Festmusik der Stadt Wien`" von Richard Strauss bis hin zu modernen Arrangements wie "`Birdland`" von Joe Zawinul.
Natürlich hatte auch das Jugendorchester der Musikschule nach der Pause die Gelegenheit mit zwei Stücken sein Können zu zeigen.

Nach rund 10-jähriger Vereinsmitgliedschaft verabschiedete der Musikverein im Rahmen des Krampuskonzertes Richard Smeja.
Er wurde zum Ehrenmitglied ernannt.
Die Ehrenmedaille in Bronze für die vollendete 15-jährige Mitgliedschaft bekamen Brigitte Golec, Wilhelm Herok und Clemens Nagel verliehen.
Roman Hörler Und Herbert Preyer bekamen die Ehrenmedaille in Silber für die vollendete 25-jährige Mitgliedschaft überreicht.
Bürgermeister Peter Nagel wurde mit der Ehrennadel in Silber ausgezeichnet, da er während seiner Amtszeit dem Verein immer tatkräftig zur Seite stand.
Besonders freute sich der Verein ebenfalls beim Krampuskonzert mit Leonhard Krennwallner einen Neuzugang zu begrüßen.
