---
title: "2009"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2009

Bei der Konzertmusikbewertung in Spannberg konnten in der Schwierigkeitsstufe C mit den Stücken "`Camelot`" v.
Siegmund Andraschek und "`Festival in Silber`" v. Manfred Schneider insgesamt 93,33 Punkte erreicht werden.
Damit belegte der Musikverein den zweiten Platz im Bezirk.

Eine ganz besondere Ehre wurde unserem Kapellmeister Felix Nentwich zuteil.
Für die ausgezeichneten Leistungen, die das Orchester unter seiner Leitung in den letzten Jahren bei den Konzertwertungen erzielte, bekam er bei der Jahreshauptversammlung des Niederösterreichischen Blasmusikverbandes feierlich die Dirigentennadel in Gold verliehen.
Diese Auszeichnung erhält ein Kapellmeister für das neunmalige Erreichen von mindestens 91 Punkten bei zwölf aufeinanderfolgenden Konzertmusikbewertungen.

Am 18. April veranstaltete der Musikverein erstmals mit dem Musikverein Breitstetten gemeinsam in der Sporthalle der Hauptschule die "`Nacht der Filmmusik`".
Geboten wurde eine abwechslungsreiche Reise durch die Film- und Fernsehwelt.
Highlights waren "`The Man With the Harmonica`" aus Spiel mir das Lied vom Tod, der gesangliche Auftritt von Majda Ritschl mit dem James Bond-Hit "`For Your Eyes Only`" oder "`Pirates of the Carribean`".

Der Abschnittsfeuerwehrleistungsbewerb am Samstag, den 6.
Juni wurde mit einer Abordnung des Musikvereins musikalisch eröffnet.
Gemeinsam mit dem Kirchenchor und dem Männergesangverein sorgten wir am Sonntag, den 7.
Juni für die musikalische Untermalung der Feldmesse vor dem Feuerwehrhaus anlässlich des Abschnittsfeuerwehrtags.

Am 21. Juni wurde der traditionelle Frühschoppen organisiert.
Der Tag der Blasmusik wurde am 11. September und 13.September mit einem Platzkonzert in der Arbeitergasse und der Feldmesse mit anschließender Agape im Kulturhausgarten gefeiert.
Erstmals konnten wir am 26. September das Sturmfest im Schubertpark feiern.
Bei herrlichem Wetter wurden über 100 Liter Sturm konsumiert.

Beim 18. Krampuskonzert am 5. Dezember reichte das Repertoire von "`Die Fledermaus`" über moderne Stücke wie dem Medley "`Music`" bis hin zu volkstümlichen Klängen wie etwa dem "`Gieslingen-Marsch`".
Das Jugendorchester ergänzte das Programm mit "`The Wild Old West`" und "`Little Brown Jug`".
Dabei wurden Richard Stöckl und Dennis Toth, die das Posaunenregister verstärkten, und Peter Nagel an der Tuba offiziell in den Verein aufgenommen.
Dieter Hauer wurde das Ehrenzeichen für eifrige und ersprießliche Tätigkeit in der niederösterreichischen Blasmusik, für seine mehr als 10-jährige vorbildhafte Vorstandstätigkeit, verliehen.
