---
title: "2010"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2010

Bei der Jahreshauptversammlung am 23. April wurde der neue Vorstand gewählt:

Obmann:: Wilhelm Herok
Obmann-Stv:: Clemens Nagel
Kapellmeister:: Felix Nentwich
{empty}1. Kapellmeister-Stv:: Clemens Nagel
{empty}2. Kapellmeister-Stv:: Markus Nentwich
Jugendreferent:: Oliver Petschk
Jugendreferent-Stv:: Mario Nentwich
Schriftführerin:: Carina Vymyslicky
Schriftführerin-Stv:: Simone Bintinger
Kassier:: Dieter Hauer
Kassier-Stv:: Katharina Domitzi
Archivar:: Benjamin Golec
Archivar-Stv:: Felix Nentwich
Stabführer:: Clemens Nagel

Am 16. April hatten wir die große Ehre, gemeinsam mit der Militärmusik Niederösterreich das Benefizkonzert zugunsten der Orgelrenovierung im Gutshof Prosoroff zu bestreiten.
Tags darauf nahm der Musikverein in der Schwierigkeitsstufe C an der Konzertmusikbewertung in Ebenthal teil.

Am 20. Juni wurden die Gäste von der Blasmusik Bohemia beim allseits beliebten Frühschoppen unterhalten.

Zum ersten Mal in der Vereinsgeschichte gaben sich mit Carina Vymyslicky und Oliver Petschk am 17. Juli zwei Vereinsmitglieder das Jawort.

Zum Tag der Blasmusik veranstaltete der Musikverein am Freitag, den 10. September, ein Platzkonzert in der Getreidegasse.
Am darauf folgenden Sonntag luden wir in gewohnter Art und Weise zur Feldmesse mit anschließendem Frühschoppen in den Kulturhausgarten.

Nach dreijähriger Pause bei der Marschmusikbewertung nahm der Musikverein am 19. September in Dürnkrut wieder an dieser Veranstaltung teil und erreichte in der Schwierigkeitsstufe C einen sehr guten Erfolg.
Am 25. September fand das Sturmfest wegen schlechtem Wetter im überdachten Garten des Kulturhauses statt.

Anlässlich des Vereinsausflugs brachen wir am 9. Oktobernach Baden auf, wo wir eine interessante Stadtführung genießen konnten.
Nach der Besichtigung der Zinnfigurenwelt in Katzelsdorf ging es in den "`KRAXL`"-Park Mönichkirchen.
Diesen ereignisreichen Tag ließen wir im Hubertuskeller Weingut Reischer in Bad Vöslau stimmungsvoll ausklingen.

Den Abschluss des Jahres bildete wie gewohnt das Krampuskonzert am 4. Dezember unter der Führung von mittlerweile drei Kapellmeistern: Felix Nentwich, Clemens Nagel und Markus Nentwich.
Veronika Borns (Querflöte), Lilith Knaus (Saxophon), Lukas Kosour (Trompete) sowie Heinz Sammer und Pascal Freiberg (beide Schlagzeug) wurden in den Verein aufgenommen.
