---
title: "2011"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2011

Eröffnet wurde das Jahr mit der äußerst gut besuchten "`Nacht der Filmmusik`", die zum ersten Mal in Zusammenarbeit mit der Ortsmusik Franzensdorf veranstaltet wurde.
Auf der Leinwand begegneten wir bekannten Filmfiguren aus "`Mission Impossible`", "`Dr. Schiwago`" oder "`Star Wars`", durchquerten mit Captain Jack Sparrow die sieben Weltmeere und kämpften mit Harry Potter gegen das Böse.
Das besondere Highlight des Abends waren "`Lion King`" und "`Bodyguard`", gesungen von Elke Nagl.
Natürlich durften auch beide Jugendorchester bei der Veranstaltung nicht fehlen.

In diesem Jahr trat der Musikverein in der Schwierigkeitsstufe B bei der Konzertmusikbewertung in Gänserndorf an.
Erstmals präsentierten wir uns unter der Leitung des erst 16-jährigen Kapellmeister-Stellvertreters Markus Nentwich.
Wir erreichten mit dem Pflichtstück "`Hallowstone Rhapsody`" von Leander Hopf und dem Selbstwahlstück "`Lexicon`" von Ed Huckeby 91,83 Punkte.

Am 29. Mai lud der Musikverein zu seinem alljährlichen Frühschoppen in den Garten des Kulturhauses.
Bei der Marschmusikbewertung am 18. September in Gänserndorf erreichten wir in der Schwierigkeitsstufe C 72,5 Punkte.
Zu unserer großen Freude konnten wir in diesem Jahr das Sturmfest am 24. September wieder im wunderschönen Schubertpark veranstalten.

Am 1. Oktober traten wir beim Marchfelder Oktoberfest im Gutshof Prosoroff, veranstaltet vom Gasthaus zur Zuckerfabrik, auf.
Nach dem musikalischen Einzug ins Festzelt wurden die Gäste vom Musikverein mit Stimmungsmusik bestens unterhalten.

Den krönenden Abschluss des Jahres bildete am 3. Dezember im Gasthaus List unser Jubiläumskonzert, das 20. Krampuskonzert seit 1992.
Vor vollen Rängen wurden die besten Stücke der vergangenen zwei Jahrzehnte unter der Leitung unserer drei Kapellmeister dargeboten.

Zu diesem Anlass wurden gleich 7 neue Mitglieder im Verein aufgenommen: Adrian Bezdekovsky (Tuba), Barbara Borns (Tenorhorn), Iris Borns (Trompete), Ines Halper (Klarinette), Verena Halper (Flügelhorn), Bernhard Kovarik (Trompete) und Leonard Kovarik (Horn).
Herr Alois Guca erhielt für die jahrzehntelange äußerst großzügige Unterstützung das Vereinsabzeichen in Silber.

Für eine vollendete 15-jährige aktive Musikausübung wurden Carina Petschk und Benjamin Golec seitens des NÖ Blasmusikverbandes mit der Ehrenmedaille in Bronze ausgezeichnet.
Als großen Gönner des Vereins wurde Alexej Prosoroff die Förderernadel in Silber des NÖBV überreicht.
