---
title: "2012"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2012  Bei der Konzertmusikbewertung am 21.
April in Hohenau konnte der Musikverein unter der Leitung von Kpm.-Stv. Markus Nentwich in der Stufe B 90,83 Punkte erreichen.
Gespielt wurden "`Kleine Alpenfantasie`" und "`Petra-Clara`".

Am 5. Mai wurden wir vom Musikverein St. Peter-Freienstein zu einem Gästekonzert in die wunderschöne Steiermark eingeladen.
Die Einladung wurde prompt mit einem Ausflug verbunden und so konnten wir zuvor noch den Erzberg erkunden.
Auch der Frühschoppen am 3. Juni durfte im Jahreskreis nicht fehlen.

Am 12. August verstarb unser ehemaliger Obmann und Ehrenmitglied Heinrich Moskwyn, den wir mit allen Ehren in Leopoldsdorf zu Grabe geleiteten.

Als Highlight der bisherigen Vereinsgeschichte durfte der Musikverein erstmals das Bezirksmusikfest der Bezirksarbeitsgemeinschaft Gänserndorf veranstalten.
In Kooperation mit dem Gasthaus zur Zuckerfabrik wurde dieses musikalische Großereignis im Rahmen des 3. Marchfelder Oktoberfests von 14.-16. September gefeiert:  Am Freitag brachten "`Franky Leitner`" und "`Die Edlseer`" mit ihren heimatverbundenen Liedtexten das Festzelt zum Kochen.
Den Samstag eröffnete der Musikverein mit Einmarsch und zünftiger Bierzeltmusik.
Für beste Wiesnstimmung sorgte der Auftritt der "`Alpenrebellen`".
Am Sonntag fanden eine traditionelle Feldmesse und ein Frühschoppen der Stadtkapelle Gloggnitz statt.
Beim darauffolgenden Bezirksmusikfest mit Marschmusikbewertung durften wir 30 Musikkapellen und zahlreiche hochrangige Ehrengäste am Rathausplatz begrüßen! Derart viele Musikvereine hatten bis dato noch nie an einem Bezirksmusikfest in Niederösterreich teilgenommen, daher freut es uns umso mehr, dass wir diesen Rekord in Leopoldsdorf aufstellen konnten.

Bei unserem Heimspiel präsentierten wir als Showfigur 2 Eheringe mit dem dazu passenden Stück "`Matrimony`" und konnten bei der Marschmusikbewertung in der höchsten Schwierigkeitsstufe E mit 93 Punkten einen ausgezeichneten Erfolg verbuchen! Zu diesem Anlass wurden auch die neue Schärpe des Vereins und der neue Tambourstab, gespendet von Stabführer Clemens Nagel, eingeweiht.

Abgeschlossen wurde dieser ereignisreiche Tag von der "`Blaskapelle Marchfeld`".

Mehr als 4000 Besucher an drei Festtagen machten dieses Fest zur größten Veranstaltung in der bisherigen Geschichte der Marktgemeinde Leopoldsdorf!
Am 1. Dezember veranstaltete der Musikverein das traditionelle Krampuskonzert im Gasthaus List.
Das Programm reichte von Johann Strauss‘ "`Kaiserwalzer`" und den virtuosen Klängen des "`Boleros`" von Maurice Ravel, bis hin zu modernen Pop- & Rockklängen von Whitney Houston und den Beatles.

Im Rahmen des Krampuskonzertes wurden folgende neue Mitglieder in den Verein aufgenommen: Lisa Riegler (Klarinette), Verena Freiberg (Querflöte) und Werner Borns (Posaune).

Als große Gönner des Vereins wurden Gerhard Krammer und Helmut Mötz mit der Förderernadel in Silber des NÖ Blasmusikverbandes ausgezeichnet.

Für die jahrelange äußerst großzügige Unterstützung des Vereins durch die Marktgemeinde Leopoldsdorf wurde Bürgermeister Thomas Nentwich feierlich die Förderernadel in Gold des NÖ Blasmusikverbandes verliehen.
