---
title: "2013"
date: 2018-10-14T22:22:57Z
draft: false
---
= 2013

Am 22. Februar 2013 wurde von der Generalversammlung folgender neuer Vorstand gewählt:

Obmann:: Wilhelm Herok
Obmann-Stv:: Andreas Turecek
Kapellmeister:: Markus Nentwich
Kapellmeister-Stv:: Felix Nentwich
Jugendreferent:: Oliver Petschk
{empty}1. Jugendreferent-Stv:: Konstantin Ilijin
{empty}2. Jugendreferent-Stv:: Mario Nentwich
Schriftführerin:: Carina Vymyslicky
Schriftführerin-Stv:: Barbara Borns
Kassier:: Katharina Domitzi
Kassier-Stv:: Matthias Kohlhuber
Archivar:: Felix Nentwich
Archivar-Stv:: Simone Bintinger
Stabführer:: Clemens Nagel
Stabführer-Stv:: Mario Nentwich

Im Rahmen dieser Neuwahlen legte Felix Nentwich nach 21 erfolgreichen Jahren sein Amt als Kapellmeister zurück und wurde vom Verein einstimmig zum Ehrenkapellmeister ernannt.

Am 9. Juni lud der Musikverein zu seinem alljährlichen, beliebten Frühschoppen in den Garten des Kulturhauses.
Bei Speis und Trank konnte das Publikum die Klänge der Blasmusik Bohemia und des Musikvereins genießen.

Am 12. Juni erhielt der Musikverein für seine fortwährend konstanten, ausgezeichneten Leistungen den Ehrenpreis in Gold vom Landeshauptmann für 2100 erreichte Punkte bei NÖBV - Veranstaltungen.

Den 2-tägigen Vereinsausflug vom 6. - 7. Juli verbrachten wir in Ramsau am Dachstein.
Am ersten Tag ging es mit der Dachstein Südwandbahn auf den Dachstein, wo wir den Skywalk und den Eispalast besichtigten.
Nach einem urigen Hüttenabend auf der Sonnenalm wanderten wir am zweiten Tag durch die Wilden Wasser zum Riesachsee.

Völlig unerwartet verstarb Ende Juli unser ehemaliger Obmann und Ehrenmitglied Johann Schöner, von dem wir uns am 1.August mit dem "`Mars de Medici`" am Friedhof Obersiebenbrunn für immer verabschieden mussten.

Bei der Marschmusikwertung in Deutsch Wagram erreichten wir mit unserem anspruchsvollen Programm in der höchsten Stufe E mit 94 Punkten, das zweitbeste Ergebnis des Bezirkes, einen ausge­zeichneten Erfolg.
Unser Gönner Alexej Prosoroff spendete dem Musikverein ein neues Flügelhorn.

Am 30. November veranstaltete der Musikverein das 22. Krampuskonzert.
Zur Aufführung gebracht wurden Stücke wie der Florentiner Marsch und klassische Musik aus den Opern "`Carmen`", "`Aida`" und "`Tannhäuser`", aber auch Schlager von Udo Jürgens und Filmmusik aus James Bond-Filmen.
Ronald Schierer wurde mit der Fördernadel des Blasmusikverbandes in Silber für seine jahrelange Unterstützung ausgezeichnet.
Für 15 Jahre Tätigkeit im Blasmusikverband erhielt Matthias Kohlhuber die Ehrenmedaille in Bronze.
Weiters durften wir Brigitte Roser, Clemens Nagel und Wilhelm Herok mit dem Vereinsabzeichen in Silber, sowie Roman Hörler mit dem Vereinsabzeichen in Gold ehren.
